#!/bin/sh

CLASSPATH="$CLASSPATH:/usr/share/java/jhdfview.jar"

CLASSPATH="$CLASSPATH:/usr/lib/java/jhdf.jar:/usr/lib/java/jhdf5.jar"

CLASSPATH="$CLASSPATH:/usr/share/java/jhdfobj.jar"
CLASSPATH="$CLASSPATH:/usr/share/java/jhdf4obj.jar:/usr/share/java/jhdf5obj.jar"

LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/lib/jhdf:/usr/lib/jhdf5:/usr/lib64/jhdf:/usr/lib64/jhdf5"

export CLASSPATH
export LD_LIBRARY_PATH

java -Xmx1000m ncsa.hdf.view.HDFView $*

